### ISSUE TITLE
Auto-migrate fails to perform on the same object more than twice

### ISSUE THREAD

**Issue by tomfeigin** [go-gorm/postgres#102]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/472

## Description
Auto-migration fails on the third change of the same object, this happens for very simple migrations.
The issue started with `gorm` version `1.23.5`, it did not occur for us in version `1.23.4`.

The test case is running multiple migration steps on the same object, first creating the object then adding a new field and finally adding a second new field. The final step fails with: `ERROR: cached plan must not change result type (SQLSTATE 0A000)`
```golang
func CreateObject() error {
	type Object struct{}
	return DB.AutoMigrate(&Object{})
}

func AddField1() error {
	type Object struct {
		Field1 string
	}
	return DB.AutoMigrate(&Object{})
}

func AddField2() error {
	type Object struct {
		Field2 string
	}
	return DB.AutoMigrate(&Object{})
}

func TestGORM(t *testing.T) {
	if DB.Dialector.Name() != "postgres" {
		return
	}
	if err := CreateObject(); err != nil {
		t.Errorf("FAILED CREATING OBJECT")
		return
	}
	if err := AddField1(); err != nil {
		t.Errorf("FAILED ADDING FIELD1")
		return
	}
	if err := AddField2(); err != nil {
		t.Errorf("I am sad :(")
		return
	}
}
```

**Comment by AlessandroSechi** [comment]
Reproduced same issue on 4bf8c572d2a21af8fdaa0731ecb2e8596f1f408b
