### ISSUE TITLE
 gorm/postgres driver1.4.6 and pgx v5 in parallel panics 

### ISSUE THREAD

**Issue by markuspatrick** [go-gorm/postgres#155]
Using Gorm with the Postgres driver 1.4.6 and pgx@v5 in parallel within a program leads to a panic (see below). With version 1.4.5 or lower parallel using works. 

`panic: sql: Register called twice for driver pgx

goroutine 1 [running]:
database/sql.Register({0x17c8c7e, 0x3}, {0x18bb180, 0xc00012b098})
        /usr/local/opt/go/libexec/src/database/sql/sql.go:51 +0x13d
github.com/jackc/pgx/v5/stdlib.init.0()
        /Users/DrKalb/.go/pkg/mod/github.com/jackc/pgx/v5@v5.2.0/stdlib/sql.go:88 +0x85

Process finished with the exit code 2
`

**Comment by leerosen-cape** [comment]
Also seeing this, seems pretty breaking

**Comment by yywing** [comment]
In my case:
I update to 1.5.0 ues pgx v5.
And I use another pkg required pgx v4.

It cause this error.

**Comment by a631807682** [comment]
https://github.com/jackc/pgx/issues/1480
https://github.com/jackc/pgx/pull/1498
https://github.com/jackc/pgx/pull/1504

This is a pgx issues, we have updated the dependencies, you can try again.
https://github.com/go-gorm/postgres/pull/175
