### ISSUE TITLE
New version is using gorm side branch

### ISSUE THREAD

**Issue by dushnik** [go-gorm/postgres#168]
Hi,

The new driver version v1.5.0 is using the gorm side branch "gorm.io/gorm v1.24.7-0.20230306060331-85eaf9eeda11".
You can see it in the go.mod file.
I think that this commit was already merged to the main banch. Is it possible to fix it?
Thanks
Dina.

**Comment by a631807682** [comment]
We regularly maintain version changes through github action, of course you are welcome to create a PR to fix it.

**Comment by dushnik** [comment]
Se my PR: https://github.com/go-gorm/postgres/pull/170
