### ISSUE TITLE
Breaking change by new gorm error translation.

### ISSUE THREAD

**Issue by farshad-sepehrara** [go-gorm/postgres#169]
This change:

https://github.com/go-gorm/postgres/commit/ecae8303f6a14860b0010b1be54a647de2590d9a

will break errors we previously considered to be returned from gorm API.
e.g. we consider postgres-pgx "unique constraint violation" to be returned from gorm but now it is translated to some gorm error (which doesn't wrap the original pgx error).
Sorry I didn't include playground link because I thought the behaviour change is obvious.

**Comment by rverdile** [comment]
I'm experiencing a similar issue. Previously, I could parse pgConn.pgError for the constraint name and handle each constraint violation differently. The ability to see the constraint name again would be appreciated.

**Comment by jinzhu** [comment]
This feature is not enabled by default in latest release.
