### ISSUE TITLE
WithoutReturning set true, select panic

### ISSUE THREAD

**Issue by ppanphper** [go-gorm/postgres#177]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/1

## Description
![image](https://user-images.githubusercontent.com/6057923/234290543-f67af53b-ff14-4935-97fe-f125fd5416b9.png)
当设置 WithoutReturning = true

没有执行注册默认callback callbacks.RegisterDefaultCallbacks

select insert等操作会报panic

**Comment by ppanphper** [comment]
![image](https://user-images.githubusercontent.com/6057923/234291623-55277624-b997-4653-af28-3972451be029.png)
我目前的解决方式

**Comment by ppanphper** [comment]
可以学习一下mysql组件的写法

![image](https://user-images.githubusercontent.com/6057923/234295376-56143c08-cc61-48bf-bb1f-c72b7845b78d.png)

**Comment by a631807682** [comment]
Can you provide reproduction code? In fact, if not registered, the default clauses will be used.
https://github.com/go-gorm/gorm/blob/master/callbacks/callbacks.go#L27

**Comment by ppanphper** [comment]
当我设置WithoutReturning = true
同时使用Scan方法，会出现panic

**Comment by ppanphper** [comment]
`
postgresConfig := postgres.New(postgres.Config{
		PreferSimpleProtocol: true,
		DSN:                  dsn,
		WithoutReturning:     true,
	})
	db, _ := gorm.Open(postgresConfig, &gorm.Config{})
var data = map[string]interface{}{}
sql := `select * from table where condition`

db.Raw(sql).Scan(&data)
`

**Comment by ppanphper** [comment]
![image](https://user-images.githubusercontent.com/6057923/234445987-bfa34e58-83ac-4410-951f-3cdffecbd484.png)
fns is nil

**Comment by a631807682** [comment]
After this https://github.com/go-gorm/gorm/commit/af3fbdc2fcfface01ce2a0795ee0fac3997ddc8e change, whether to support return is specified by the clauses, which means that we cannot support those that neither support returning (or the user does not want return), nor support Database of [LastInsertId](https://github.com/go-gorm/gorm/blob/master/callbacks/create.go#L109)

cc @jinzhu
