### ISSUE TITLE
use DriverName but unkonw driver

### ISSUE THREAD

**Issue by zzy2210** [go-gorm/postgres#183]
## Your Question

I tried to use other drivers by way of the “drivername” parameter.

but it return error "sql: unknown driver"

What should I do?

## The document you expected this should be explained
the code like :
``` go
import (
	"fmt"

	"gorm.io/driver/postgres"
	"gorm.io/gorm"

	_ "gitee.com/opengauss/openGauss-connector-go-pq"
)

func NewClient() (*gorm.DB, error) {
	return gorm.Open(postgres.New(postgres.Config{
		DSN:                  fmt.Sprintf(dsnLayout, ip, user, password,dbname,port),
		PreferSimpleProtocol: true, // disables implicit prepared statement usage
		DriverName:           "openGauss-connector-go-pq",
	}), &gorm.Config{})
}

```

**Comment by saeidee** [comment]
You might try it like this:

```go
return gorm.Open(postgres.New(postgres.Config{
		DSN:                  fmt.Sprintf(dsnLayout, ip, user, password,dbname,port),
		PreferSimpleProtocol: true, // disables implicit prepared statement usage
		DriverName:           "opengauss",
	}), &gorm.Config{})
```

**Comment by zzy2210** [comment]
> You might try it like this:
> 
> ```go
> return gorm.Open(postgres.New(postgres.Config{
> 		DSN:                  fmt.Sprintf(dsnLayout, ip, user, password,dbname,port),
> 		PreferSimpleProtocol: true, // disables implicit prepared statement usage
> 		DriverName:           "opengauss",
> 	}), &gorm.Config{})
> ```

thanks~
i will try it
