### ISSUE TITLE
breaking changes w/ the 0.2.5 change to pgx?

### ISSUE THREAD

**Issue by ItsLeeOwen** [go-gorm/postgres#2]
## Your Question

go.sum
```
gorm.io/datatypes v0.0.0-20200620103158-546ecd30e4ba // indirect
gorm.io/driver/postgres v0.2.5
gorm.io/gorm v0.2.19
```

I'm not sure if encountering bugs as a result of the v0.2.5 switch to `pgx` or if there is required migration to support the change.  

Given the following struct...

```go
type Harumph struct {
	gorm.Model
	Thing     *Thing `gorm:"type:jsonb" json:",omitempty"`
}

type Thing map[string]interface{}
```
### 1)
Thing `Valuer` no longer works for the `jsonb` column unless typecast the marshaled `[]byte` to `string`
```go
func (m *Thing) Value() (driver.Value, error) {
	return json.Marshal(m)
}
```
```
ERROR: could not parse JSON: unable to decode JSON: invalid character '\\\\' looking for beginning of value (SQLSTATE 22P02)
```

But this works
```go
func (m *Thing) Value() (driver.Value, error) {
	b, err := json.Marshal(m)
	return string(b), err
}
```

### 2)
When implementing Thing `Scanner`, Scan is called, and appears to update the value of *Thing, but the value of Harumph.Thing is still nil.
```go
func (m *Thing) Scan(src interface{}) error {
	b, ok := src.([]byte)
	if !ok {
		return errors.New("byte assertion failed")
	}

	var value Thing
	if err := json.Unmarshal(b, &value); err != nil {
		return err
	}

	*m = value

	return nil
}
```

### 3)
Scan triggers a `Valuer` call error when using non-pointer reference 
```go
func (m Thing) Value() (driver.Value, error)
```
```
value method Thing.Value called using nil *Thing pointer
```

I don't believe `Value` should require a pointer reference, but Thing.Value will work if changed to pointer *Thing
```go
func (m *Thing) Value() (driver.Value, error)
```

## Expected answer

Looking to understand whether there are bugs w/ the 0.2.5 pgx switch, or new requirements with the change.

**Comment by jinzhu** [comment]
Seems like the JSON implementation of https://github.com/go-gorm/datatypes/blob/master/json.go pass tests, so this happened because there are some data created with old driver?

**Comment by ItsLeeOwen** [comment]
ok thanks, I'll review more
