### ISSUE TITLE
How can I disable WithReturning config before insert queries?

### ISSUE THREAD

**Issue by ismailakbudak** [go-gorm/postgres#20]
## Your Question

I want to use this package for RedShift database. It works very well for simple queries. But the redshift db does not support `RETURNING` part on insert queries and it fails with ` ERROR: syntax error at or near "RETURNING" (SQLSTATE 42601)
` error.  
```go
func (dialector Dialector) Initialize(db *gorm.DB) (err error) {
	// register callbacks
	callbacks.RegisterDefaultCallbacks(db, &callbacks.Config{
		WithReturning: true,
	})
        //.....
}
```

## Expected answer

How can I disable `WithReturning: true` config as a `false` before the create operation?

**Comment by jinzhu** [comment]
Added a `WithoutReturning` option, thank you for your report.
