### ISSUE TITLE
Incorrect timezone parser

### ISSUE THREAD

**Issue by tsaikd** [go-gorm/postgres#22]
https://github.com/go-gorm/postgres/blob/566aa2e6ed74ccb7198183e40f4a40bdb26c8d51/postgres.go#L64

Recommend to use `(time_zone|TimeZone)=([^& ]+)` instead of `(time_zone|TimeZone)=(.*)($|&| )`.

See the following example in the playground.

https://play.golang.org/p/cExzVVo_j3P

**Comment by jinzhu** [comment]
Fixed, thank you for your report.
