### ISSUE TITLE
bug: postgres driver tries to insert slices and arrays as records, and fails (reproduction included)

### ISSUE THREAD

**Issue by sleddev** [go-gorm/postgres#229]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/668

## Explain your user case and expected results
When inserting go arrays or slices in a GORM model, the generated SQL uses them as records, so the insert fails.

For example:
```go
type Test struct {
	Data []float64 `gorm:"type:float8[]"`
}

test := Test{Data: []float64{8, 4, 2, 1, 0.5}}
DB.Create(&test)
```
gives the SQL:
```sql
INSERT INTO "tests" ("data") VALUES ((8,4,2,1,0.5))
```
And I get the error `ERROR: column "data" is of type double precision[] but expression is of type record (SQLSTATE 42804)`

Instead, the SQL should be:
```sql
INSERT INTO "tests" ("data") VALUES ('{8,4,2,1,0.5}')
```
or
```sql
INSERT INTO "tests" ("data") VALUES (ARRAY [8,4,2,1,0.5])
```

If I use pgx directly, and do:
```go
conn, err := pgx.Connect(...)

arr := []float64{8, 4, 2, 1, 0.5}
_, err = conn.Exec(context.Background(), "INSERT INTO tests (data) VALUES($1)", arr)
```
It works as expected, generating SQL with the `'{...}'` syntax

**Comment by carlcris** [comment]
i encountered the issue, @sleddev did you manage to sort it out?

**Comment by sleddev** [comment]
@carlcris I ended up making type aliases, and implementing my own `Scan` and `Value` functions on those types.

Here's my current implementation: https://gist.github.com/sleddev/17ddd0e5f2a037ecf7bb6527367cb916

There may be edge cases I didn't account for, but from my testing and usage works nicely.

To use it, just swap `[]float64` to `pg.Float8Array` in your model

**Comment by linfengOu** [comment]
Is this issue resolved? I'm still facing the same issue in 1.25.12

**Comment by MrGuoRanDuo** [comment]
I'm still facing the same issue in 1.5.11

**Comment by MrGuoRanDuo** [comment]
@sleddev

**Comment by MrGuoRanDuo** [comment]
@jinzhu

**Comment by jinzhu** [comment]
The solution is just like above comment `swap []float64 to pg.Float8Array in your model` or you can use gorm.io/docs/serializer.html
