### ISSUE TITLE
m.GuessConstraintInterfaceAndTable undefined

### ISSUE THREAD

**Issue by husamettinarabaci** [go-gorm/postgres#243]
https://github.com/go-gorm/postgres/commit/1cfbc8652cd8c56d1cd05c1a3e111318b3dd551d

/go/pkg/mod/gorm.io/driver/postgres@v1.5.5/migrator.go:411:26: m.GuessConstraintInterfaceAndTable undefined (type Migrator has no field or method GuessConstraintInterfaceAndTable)

I am getting this in CI/CD. It didn't pass to test.

**Comment by Tuki277** [comment]
I encountered the same error. How to fix ?

**Comment by reality95** [comment]
> I encountered the same error. How to fix ?

Revert to 1.5.4
