### ISSUE TITLE
Updating to `jackc/pgx/v5@v5.5.3` causes issues

### ISSUE THREAD

**Issue by patrykgz** [go-gorm/postgres#245]
## Description

Upgrading to `jackc/pgx/v5@v5.5.3` causes build errors:

```../../../../pkg/mod/gorm.io/driver/postgres@v1.5.5/migrator.go:411:26: m.GuessConstraintInterfaceAndTable undefined (type Migrator has no field or method GuessConstraintInterfaceAndTable)```

**Comment by reinkrul** [comment]
We encountered the same, upgrading from `v1.5.4` to `v1.5.5`.

**Comment by J-Rocke** [comment]
@patrykgz See https://github.com/go-gorm/postgres/issues/244 and https://github.com/go-gorm/postgres/issues/247 for more information. I think this is a duplicate and can be closed.
