### ISSUE TITLE
CVE GO-2024-2606 - Need to bump `pgx` version

### ISSUE THREAD

**Issue by LJ-Software** [go-gorm/postgres#260]
## CVE Link

https://github.com/jackc/pgx/security/advisories/GHSA-mrww-27vc-gghv
and
https://pkg.go.dev/vuln/GO-2024-2606

## Description

There is a public CVE for [github.com/jackc/pgx](https://pkg.go.dev/github.com/jackc/pgx) that can be remedied by updating pgx to `v5.5.4`.

## Solution

Update dependency pgx to version > v5.5.4

**Comment by 91pavan** [comment]
@jinzhu can you please release a new version for GORM?
