### ISSUE TITLE
Use postgres double precision for Golang float64

### ISSUE THREAD

**Issue by onwsk8r** [go-gorm/postgres#28]
It looks like fields declared as `float` without a scale or precision are migrated/created as SQL `decimal`:

https://github.com/go-gorm/postgres/blob/e5522436e33bcc2e1e7aae3a9d2bdb1bbd7b426e/postgres.go#L140-L147

Which is an arbitrary precision type that is identical to `numeric`, according to [the docs](https://www.postgresql.org/docs/current/datatype-numeric.html):

> The types decimal and numeric are equivalent. Both types are part of the SQL standard.

Using `numeric` for fields with defined scale/precision makes sense - those are the only arbitrary precision types - but it creates a disconnect between Golang floats and their database analogs in other cases. Namely, floating point numbers such as SQL `real` and `double precision`, which are analogous to Go's `float32` and `float64`, respectively, are defined by [IEEE 754](https://en.wikipedia.org/wiki/IEEE_754) - as is their behavior.

- Floating point numbers don't always translate exactly to arbitrary precision (the opposite is obviously also true) - sometimes it's nice to not have an extra `.00000007` appended to our values
- Arbitrary precision types in Postgres have nonstandard mathematical behavior (eg with rounding) - it's nice to know that moving simple maths to Postgres won't change the result of the equation
- Arbitrary precision math is extremely slow, which is one of the main advantages of fixed precision - do you use Go's `big.Float` every time you want to add a couple of real numbers?

That all being said, is there a reason for this behavior? It would be nice to change it, but I understand that would have far-reaching consequences - you can't alter a column from arbitrary to fixed precision!

**Comment by fc-ds** [comment]
Is there any update on this ?

I try to convert pg double precision to float64 via gorm and it does not work.

**Comment by jinzhu** [comment]
from the description, would like to keep it like now. 

https://www.postgresql.org/docs/9.1/datatype-numeric.html

**Comment by kbolino** [comment]
There should at least be an option to choose the underlying type here, since after all `float64` and `double precision` are exactly the same type.
