### ISSUE TITLE
sql: unknown driver "postgres"

### ISSUE THREAD

**Issue by piLinux** [go-gorm/postgres#51]
## Your Question

```
import (
  "database/sql"

  "gorm.io/gorm"
  "gorm.io/gorm/logger"
  "gorm.io/driver/postgres"
)

func abc() {
  ... ... ...
  sqlDB, err = sql.Open("postgres", dsn)

  db, err = gorm.Open(postgres.New(postgres.Config{
    Conn: sqlDB,
     }), &gorm.Config{})
... ... ...
}
```

It fails to establish a connection with the PostgreSQL database.

Error message:
`sql: unknown driver "postgres" (forgotten import?)`

## The document you expected this should be explained

[official documents site](https://gorm.io/docs/connecting_to_the_database.html)

## Expected answer

With MySQL and SQLite3 drivers `gorm.io/driver/mysql`, `gorm.io/driver/sqlite`, everything works perfectly fine.

## Temporary workaround

By importing `_ "github.com/jinzhu/gorm/dialects/postgres"` along with `"gorm.io/driver/postgres"`, connection with PostgreSQL database works smoothly.

So, why isn't `"gorm.io/driver/postgres"` works without importing `_ "github.com/jinzhu/gorm/dialects/postgres"` ? Am I missing something?

Thank you in advance.

**Comment by sebastianbuechler** [comment]
Why are you using `database/sql`? For me it works when calling directly `db, err := gorm.Open(postgres.Open(dsn), &gorm.Config{})`

**Comment by piLinux** [comment]
> Why are you using `database/sql`? For me it works when calling directly `db, err := gorm.Open(postgres.Open(dsn), &gorm.Config{})`

https://pkg.go.dev/gorm.io/driver/postgres@v1.1.0?utm_source=gopls#Config

```
type Config struct {
	DriverName           string
	DSN                  string
	PreferSimpleProtocol bool
	WithoutReturning     bool
	Conn                 *sql.DB
}
```

For custom configurations (example: max number of connections in the idle connection pool, max number of open connections in the database, etc.), I am using `database/sql`.

**Comment by sebastianbuechler** [comment]
Did you try to use the gorm implementation of these features as seen here? https://gorm.io/docs/connecting_to_the_database.html#Connection-Pool

**Comment by piLinux** [comment]
> Did you try to use the gorm implementation of these features as seen here? https://gorm.io/docs/connecting_to_the_database.html#Connection-Pool

Yes exactly. You can see the full code here (facing issue only with postgres):
https://github.com/piLinux/GoREST/blob/6f54b916bc3eda95201ac5c0b456e1838693095d/database/dbConnect.go
