### ISSUE TITLE
Zero-value time is not kept

### ISSUE THREAD

**Issue by caioaao** [go-gorm/postgres#67]
## GORM Playground Link

https://github.com/go-gorm/playground/pull/393

## Description

I expect the timezone to return empty when the timestamp is empty.

**Comment by jinzhu** [comment]
Maybe use `*time.Time` or `sql.NullTime` to make it work.

**Comment by caioaao** [comment]
Making it work wasn't an issue, but it's an unexpected behavior

**Comment by jinzhu** [comment]
use `timestamptz` to store zero value of time.Time returns the invalid time, if you want to store the zero value, you can change the datatype of the field to `timestamp`.
