### ISSUE TITLE
Please bring back WithoutReturning functionality

### ISSUE THREAD

**Issue by nc-dirknilius** [go-gorm/postgres#91]
## Describe the feature

In a recent [question](https://github.com/go-gorm/postgres/issues/20), there was an issue using Gorm with AWS Redshift because of the unsupported `RETURNING` keyword. This was [resolved](https://github.com/go-gorm/postgres/commit/70e3bdf112557183a6c3caa831384f55445662c1) later, and then [removed](https://github.com/go-gorm/postgres/commit/599259408eb08bc35a9487f35ca2cafe0ff13954) again. The [option](https://github.com/go-gorm/postgres/blob/dc3ea2aaca4da232fb9e527a93ba9f71ef489deb/postgres.go#L27) in the `postgres.Config` struct is still there, but without effect.

## Motivation

Using Redshift with Gorm is still a valid use case. Don't know if the removal was an accident.

## Related Issues

https://github.com/go-gorm/postgres/issues/20
https://github.com/go-gorm/postgres/commit/70e3bdf112557183a6c3caa831384f55445662c1
https://github.com/go-gorm/postgres/commit/599259408eb08bc35a9487f35ca2cafe0ff13954

Would be cool if that can be supported again :-)

**Comment by jinzhu** [comment]
https://github.com/go-gorm/postgres/commit/d3403e488eddc0cd1792e45b2122d39e733e04aa
